name: AI Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: pip # Cải thiện tốc độ cài đặt package

      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run AI Code Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          set -e  # Dừng script nếu có lỗi
          python .github/review_script.py
